apiVersion: apps/v1
kind: Deployment
metadata:
  name: hg
  namespace: languagedepot
spec:
  template:
    spec:
      containers:
        - name: hgweb
          env:
            - name: APP_VERSION
              value: "dockerDev"
      initContainers:
        - name: populate-test-repos
          image: busybox:1.36.1
          command: [ 'sh', '-c', "if [ ! -d /repos/sena-3 ]; then wget -O sena-3.zip 'https://drive.google.com/uc?export=download&id=1I-hwc0RHoQqW774gbS5qR-GHa1E7BlsS'; unzip -q sena-3.zip -d /repos/; fi" ]
          volumeMounts:
            - name: repos
              mountPath: /repos
