name: "Run integration tests"
description: "run our full test suite"

inputs:
  hostname:
    description: "Target host to run the integration tests against"
    required: true

runs:
  using: composite
  steps:
    - name: run integration tests
      uses: ./.github/actions/dotnet-integration
      with:
        hostname: ${{ inputs.hostname }}
    - name: Upload test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always() && !env.act
      with:
        check_name: Integration Test
        files: ./testresults/*.trx
