# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
apiVersion: v1
kind: Service
metadata:
  name: hasura
  labels:
    app: hasura
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: hasura

---

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#writing-a-deployment-spec
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
  labels:
    app: hasura
spec:
  selector:
    matchLabels:
      app: hasura
  strategy:
      type: Recreate
  template:
    # https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates
    metadata:
      labels:
        app: hasura
    spec:
      containers:
      - name: hasura
        image: ghcr.io/sillsdev/lexbox-hasura
        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers
        resources:
          requests: # TODO: need to establish resource limits, possibly after seeing it in action for some regular and/or load testing
            memory: 260Mi
            cpu: 0.1
          limits:
            memory: 400Mi

        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                  key: POSTGRES_DB
                  name: db
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: db
          - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
            value: postgres://postgres:$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)
          - name: PG_DATABASE_URL
            value: $(HASURA_GRAPHQL_METADATA_DATABASE_URL)
          - name: HASURA_GRAPHQL_ADMIN_SECRET
            valueFrom:
              secretKeyRef:
                  key: HASURA_GRAPHQL_ADMIN_SECRET
                  name: hasura
