# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
apiVersion: v1
kind: Service
metadata:
  name: hgresume
  labels:
    app: hgresume
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: hgresume

---

# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hgresume-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#writing-a-deployment-spec
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hgresume
  labels:
    app: hgresume
spec:
  selector:
    matchLabels:
      app: hgresume
  strategy:
      type: Recreate
  template:
    # https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates
    metadata:
      labels:
        app: hgresume
    spec:
      containers:
      - name: hgresume
        image: ghcr.io/sillsdev/hgresume:v2023-02-24
        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers
        resources:
          requests: # TODO: need to establish resource limits, possibly after seeing it in action for some regular and/or load testing
            memory: 260Mi
            cpu: 0.1
          limits:
            memory: 400Mi

        volumeMounts:
        - name: cache
          mountPath: /var/cache/hgresume
        - name: repos
          mountPath: /var/vcs/public

      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: hgresume-cache
      - name: repos
        persistentVolumeClaim:
          claimName: hg-repos # established in hg-repos-pvc.yaml
