# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy
spec:
  defaultBackend:
    service:
      name: lexbox
      port:
        name: sveltekit
  rules:
  - host: staging.languagedepot.org
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: lexbox
            port:
              name: http
      - path: /v1/traces
        pathType: Prefix
        backend:
          service:
            name: lexbox
            port:
              name: otel

  tls:
  - hosts:
    - staging.languagedepot.org
    secretName: languagedepot-tls # provided by LTOps
