apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: languagedepot

resources:
- secrets.yaml
- pvc.yaml
- db-deployment.yaml
- hg-deployment.yaml
- lexbox-deployment.yaml
- ui-deployment.yaml
- proxy-deployment.yaml
