#file: noinspection KubernetesMissingKeys
#file is a patch file that will be applied to the base deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lexbox
  namespace: languagedepot
spec:
  template:
    spec:
      containers:
        - name: lexbox-api
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Staging"
      initContainers:
        - name: db-migrations
          env:
            - name: DOTNET_ENVIRONMENT
              value: "Staging"
