on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dotnet-integration
        with:
          hostname: staging.languagedepot.org
