name: Build and publish a lexbox api image

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/lexbox-api.yaml'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    env:
      # https://docs.docker.com/develop/develop-images/build_enhancements/
      DOCKER_BUILDKIT: 1

    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set Version
        id: setVersion
        # set version to date in vYYYY-MM-DD format
        run: |
          echo "VERSION=v$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/sillsdev/lexbox-api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            ${{ env.VERSION }}
      -
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: docker/build-push-action@v4
        with:
          context: backend
          build-args: |
            APP_VERSION=${{ env.VERSION }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
