name: Build and publish a lexbox configured hasura image

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - hasura-deployment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    env:
      # https://docs.docker.com/develop/develop-images/build_enhancements/
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and tag the image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t lexbox-hasura hasura

      - name: look around
        run: docker images
